# /.github/workflows/nodjs.yml
name: nohup runner
 
on: 
  issues:
    types:
      - labeled

jobs:
  build:
    runs-on: mc-host
    
    steps:
      - name: 'setup bukkit'
        uses: IngGameTeam/setup-bukkit@main
        id: setup-bukkit
        with:
          branch: ${{ github.event.label.name }}
          repo: ${{ github.repository }}
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "1.19"
          ram: "4500M"
          output-suffix: "output"
      - name: 'deploy bukkit'
        uses: IngGameTeam/deploy-bukkit@main
        with: 
          branch: ${{ github.event.label.name }}-output
          repo: ${{ github.repository }}
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
